# Generated by Django 5.2.3 on 2025-08-18 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(help_text='구글 계정 고유 ID', max_length=100, unique=True)),
                ('google_email', models.EmailField(help_text='구글 계정 이메일', max_length=254)),
                ('picture', models.URLField(blank=True, help_text='구글 프로필 사진 URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구글 사용자',
                'verbose_name_plural': '구글 사용자들',
            },
        ),
    ]
