# Generated by Django 5.2.3 on 2025-10-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name',
        ),
    ]
